# Generated by Django 6.0.5 on 2026-05-20 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/', verbose_name='Логотип')),
                ('verification_mode', models.CharField(choices=[('invite', 'Код школы'), ('email', 'Email домена'), ('class_code', 'Код класса'), ('manual', 'Ручная проверка')], default='invite', max_length=20)),
                ('allowed_email_domains', models.JSONField(blank=True, default=list, help_text='Например: ["school12.ru", "edu.school12.ru"]', verbose_name='Разрешённые домены email')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolInviteCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='school.school')),
            ],
            options={
                'verbose_name': 'Код приглашения',
                'verbose_name_plural': 'Коды приглашения',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Класс')),
                ('slug', models.SlugField(max_length=30)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('weekly_points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school.school')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['school', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
    ]
