# Generated by Django 6.0.5 on 2026-05-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Лайк'), ('comment', 'Комментарий'), ('class_rank', 'Рейтинг класса'), ('achievement', 'Достижение')], max_length=20),
        ),
    ]
