# Generated by Django 6.0.5 on 2026-05-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chats_messa_chat_id_b17a3f_idx',
            old_name='chats_messa_chat_id_f5a8c8_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chats_messa_sender__b92f58_idx',
            old_name='chats_messa_sender__4c2d5f_idx',
        ),
    ]
