# Generated by Django 6.0.5 on 2026-05-20 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('post', 'Пост'), ('comment', 'Комментарий'), ('like_given', 'Лайк поставлен'), ('like_received', 'Лайк получен'), ('daily_login', 'Ежедневный вход')], max_length=20)),
                ('points', models.PositiveSmallIntegerField()),
                ('reference_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_events', to='school.schoolclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие очков',
                'verbose_name_plural': 'События очков',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action', 'created_at'], name='class_clash_user_id_b20b81_idx'), models.Index(fields=['school_class', '-created_at'], name='class_clash_school__e4bcc9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference_id__isnull', False)), fields=('user', 'action', 'reference_id'), name='unique_point_event_per_reference')],
            },
        ),
    ]
