# Generated by Django 6.0.5 on 2026-05-27 14:02

import apps.class_clash.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_clash', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClashSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=apps.class_clash.models._default_season_end)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'ordering': ['-season_number'],
            },
        ),
        migrations.CreateModel(
            name='ClassBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('most_active', '🔥 Most Active'), ('fastest_growing', '⚡ Fastest Growing'), ('number_one', '👑 #1 This Week')], max_length=30)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='school.schoolclass')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='class_clash.clashseason')),
            ],
            options={
                'verbose_name': 'Значок класса',
                'verbose_name_plural': 'Значки классов',
                'ordering': ['-awarded_at'],
                'indexes': [models.Index(fields=['school_class', 'badge_type'], name='class_clash_school__a21d55_idx')],
            },
        ),
    ]
