# Generated by Django 6.0.5 on 2026-05-30 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_add_performance_indexes'),
        ('school', '0002_add_city_to_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('post_count', models.PositiveIntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Горячая тема',
                'verbose_name_plural': 'Горячие темы',
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(choices=[('fire', '🔥'), ('like', '👍'), ('laugh', '😂'), ('skull', '💀')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='engagement_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['school', 'is_pinned', '-created_at'], name='posts_post_school__8092aa_idx'),
        ),
        migrations.AddField(
            model_name='hottopic',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_topics', to='school.school'),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.post'),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hottopic',
            unique_together={('school', 'text')},
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together={('user', 'post', 'emoji')},
        ),
    ]
